### PR TITLE
Call CramItem.from_parent

### PR DESCRIPTION
**Pull request by kynan**
Directly calling the constructor of a node subclass has been deprecated in pytest 5.4: https://docs.pytest.org/en/latest/deprecations.html#node-construction-changed-to-node-from-parent

### CODE REVIEW

**Review by tbekolay — APPROVED** [review]
LGTM, thanks again!

**Comment by kynan** [comment]
@tbekolay could you release this in a new version? This is now a fatal error in pytest 6.0.

**Comment by tbekolay** [comment]
[Done](https://pypi.org/project/pytest-cram/), thanks for the heads up!

**Comment by kynan** [comment]
Thanks, Trevor!

**Pull request merged**
